config/routes.rb
Rails.application.routes.draw do
  

  root 'welcome#index'
  
  resources :hubs #name, lights, username
  resources :lights #name, id, hub
  resources :rooms #name, lights, hub
  
  

 
  

end

app/models/hub.rb
class Hub < ActiveRecord::Base
end

app/models/light.rb
class Light < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  def index
  end
  
  def show
    @hub = Hubs.find(params[:id])
    @lights = Lights.where(hub_id: params[:id])
    @light = ""
    if @lights.length == 0
      #will show that no lights have been added yet
      @light = "none found, please add lights"
    else
      @lights.each do |l|
        #lights found, creating string for display
        @light = @light + ", " + l.name
      end
    end
  end
  
  def new
  end
  
  def edit
  end
  
  def create
    #these setting can be used to define hub IP or a custom username
    #config.hue_ip = '123.456.789.012'
    #config.uuid = '0123456789abdcef0123456789abcdef' 
    
    #initializes the username, must press button afterward
    Huey::Request.register
    sleep(30)#wait 30 seconds for hub button press
    registery = Huey::Request.register
    if defined? registery[0]
      #username was whitelisted
      @hub = Hub.new
      @hub.name = hub_params[:name]
      @hub.username = registery[0]["success"]["username"]
      @hub.save
      redirect_to @hub
    else
      #button not pressed in time
      redirect_to :action=>"new"
    end
  end
    
  def update
  end
  
  def destroy
  end
  
  private
    def hub_params
      params.require(:widget).permit(:name)
    end
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController
  def index
    @lights = Lights.all
  end
  
  def show
    @light = Lights.find(params[:id])
    @details = Huey::Bulb.find(@light.light_id)
  end

  def new
  end
  
  def edit
  end
  
  def create
    #just auto adds bulbs when going to create action for now
    @light_list = Huey::Bulb.find_all("")
    @light_list.each do |l|
      @light = Light.new
      @light.name = l.name
      @light.light_id = l.id
      @light.hub_id = 1 #default for now, will need to pass hub id eventually
      @light.save!
    end
  end
  
  def update
  end
  
  def destroy
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/helpers/lights_helper.rb
module LightsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hubs/new.html.erb
<%= form_for :hub, url: hubs_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %> (press hub button after submit)
  </p>
<% end %>

app/views/hubs/show.html.erb
<p>
	Name: <%= @hub.name%><br>
	ID: <%= @hub.id%><br>
	Username: <%= @hub.username %>
	Lights: <%= @light%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightControl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lights/show.html.erb
<p>
	<h2><%= @details.name %></h2>
	ID: <%= @details.id %> <br>
	On: <%= @details.on %> <br>
	Brightness: <%= @details.bri %> <br>
	Hue: <%= @details.hue %> <br>
	Saturation: <%= @details.sat%> <br>
	XY: <%= @details.xy %> <br>
	CT: <%= @details.ct %> <br>
	Transition time: <%= @details.transitiontime %> <br>
	Color mode: <%= @details.colormode %> <br>
	Effect: <%= @details.effect %> <br>
	Reachable: <%= @details.reachable %> <br>
	Alert: <%= @details.alert %> <br>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>